<?php echo $this->nodeNavigation('CALCAT', 'list') ?>

<?php if (count($this->categories)) : ?>
	<table class="table table-hover">
		<thead>
			<tr>
				<th>ID</th>
				<th>Titel</th>
			</tr>
		</thead>
        <tbody data-link="row" class="rowlink">
            <?php foreach ($this->categories as $entity) : ?>
				<tr style="background-color: <?php echo $this->escapeHtmlAttr($entity->getBackgroundColor()) ?>; color: <?php echo $this->escapeHtmlAttr($entity->getColor()) ?>">
					<td>
                        <a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'edit', 'id' => $entity->getNodeId()), true) ?>">
                            <?php echo $this->escapeHtml($entity->getNodeId()) ?>
                        </a>
					</td>
					<td>
						<?php echo $this->escapeHtml($entity->getTitle()) ?>					
					</td>
				</tr>
			<?php endforeach ?>
		</tbody>
	</table>
<?php else : ?>
    <p><?php echo $this->translate('No entries.') ?></p>
<?php endif ?>
