<?php $today = new \DateTime() ?>
<?php $entries = $this->day->getEntries() ?>
<?php
    $lines = array();
    foreach ($this->day->getHolidays() as $holiday) {
        if ('line' == $holiday['type']) $lines[] = $holiday;
    }

?>


       <td <?php
       $css = array();
       
       if (isset($this->month) && $this->day->getDateTimeStart()->format('Y-m') != $this->month->getDateTimeStart()->format('Y-m'))
       	$css[] = 'inactive';
       if ($this->day->isHoliday())
       	$css[] = 'danger';
       if ($this->day->getDateTimeStart()->format('Y-m-d') == $today->format('Y-m-d'))
       	$css[] = 'today';
       if (isset($this->currentMonth) && $this->day->getDateTimeStart()->format('m') != $this->currentMonth)
           $css[] = 'inactive';
       if ($css) echo 'class="'.implode(' ', $css).'"';
       
       if ($lines) echo 'style="padding-top: 1px"';
       
      ?>>
      
	<?php foreach ($lines as $holiday) : ?>
       		<div class="day-line" title="<?php echo $this->escapeHtmlAttr($holiday['label']) ?>" style="background-color: <?php echo $this->escapeHtmlAttr($holiday['color']) ?>"></div>
       <?php endforeach ?>
       
      
      <?php 
       // Time spans
       foreach ($entries as $entry) {
            if (! $entry->getDateTime2() || $entry->getDateTime1()->format('Y-m-d') == $entry->getDateTime2()->format('Y-m-d')) continue;
            
            if ($this->day->getDateTimeStart()->format('Y-m-d') >= $entry->getDateTime1()->format('Y-m-d')
                && $this->day->getDateTimeStart()->format('Y-m-d') <= $entry->getDateTime2()->format('Y-m-d')) {
                    echo $this->partial('kofus/calendar/calendar/day/entry.phtml', array('entry' => $entry, 'isPeriod' => true));
            }
       }
       ?>
       

       <?php foreach ($this->day->getHolidays() as $holiday) : ?>
           <?php if ($holiday['type'] !== 'icon') continue ?>
           
           <?php if ($holiday['label'] == 'new') : ?>
               <i class="wi wi-moon-new pull-left" data-toggle="tooltip" title="Neumond" style="color: gray"></i>
           <?php elseif ($holiday['label'] == 'full') : ?>
               <i class="wi wi-moon-full pull-left" data-toggle="tooltip" title="Vollmond" style="color: gray"></i>
           <?php elseif ($holiday['label'] == 'waxing') : ?>
               <i class="wi wi-moon-waxing-crescent-4 pull-left" data-toggle="tooltip" title="Zunehmender Mond" style="color: gray"></i>
           <?php elseif ($holiday['label'] == 'waning') : ?>
               <i class="wi wi-moon-waning-crescent-2 pull-left" data-toggle="tooltip" title="Abnehmender Mond" style="color: gray"></i>
               
           <?php endif ?>
           
       <?php endforeach ?>
       <?php
            $today = new \DateTime();
            $dt = $this->day->getDateTimeStart();
            $day = $this->nodes()->getRepository('DAY')->findOneBy(array('date' => $dt));
            if (! $day && ($dt->format('Y-m-d') == $today->format('Y-m-d'))) {
                $day = new \BackOffice\Entity\DayEntity();
                $day->setDate($today);
                $this->em()->persist($day);
                $this->em()->flush();
            }
 
       ?>
       <?php if ($day) : ?>
	       <strong class="pull-right">
	       	<a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'edit', 'id' => $day->getNodeId())) ?>">
	       		<?php echo $this->day->getDateTimeStart()->format('d') ?></strong><br>
	       	</a>
       <?php else : ?>
	       <strong class="pull-right"><?php echo $this->day->getDateTimeStart()->format('d') ?></strong><br>
       <?php endif ?>
       
       	                           

       <?php foreach ($this->day->getHolidays() as $holiday) : ?>
                  <?php if ($holiday['type'] != 'text') continue ?>
           <?php echo $holiday['label'] ?><br>
       <?php endforeach ?>

       <?php foreach ($entries as $entry) : ?>
            <?php if ('CALENTB' == $entry->getNodeType()) : ?>
                <a title="<?php echo $this->escapeHtmlAttr($entry->getTitle()) ?>" class="label label-warning" href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'edit', 'id' => $entry->getNodeId()), true) ?>">
                   <?php echo $entry->getTitle(20) ?>
                   <?php if ($entry->getAge($this->day->getDateTimeStart())) : ?>
                        (<?php echo $this->escapeHtml($entry->getAge($this->day->getDateTimeStart())) ?>)
                   <?php endif ?>
                </a><br>
            <?php elseif (! $entry->getDateTime2() || $entry->getDateTime2()->format('Y-m-d') == $entry->getDateTime1()->format('Y-m-d')) : ?>
                <?php echo $this->partial('kofus/calendar/calendar/day/entry.phtml', array('entry' => $entry)) ?>
           <?php endif ?>
       <?php endforeach ?>
       </td>


