<?php $today = new \DateTime() ?>
<?php $entries = $this->day->getEntries() ?>


       <td <?php
       $css = array();
       
       if (isset($this->month) && $this->day->getDateTimeStart()->format('Y-m') != $this->month->getDateTimeStart()->format('Y-m'))
       	$css[] = 'inactive';
       if ($this->day->isHoliday())
       	$css[] = 'danger';
       if ($this->day->getDateTimeStart()->format('Y-m-d') == $today->format('Y-m-d'))
       	$css[] = 'today';
       if (isset($this->currentMonth) && $this->day->getDateTimeStart()->format('m') != $this->currentMonth)
           $css[] = 'inactive';
       if ($css) echo 'class="'.implode(' ', $css).'"';
       
      ?>>
      
      <?php 
       // Time spans
       foreach ($entries as $entry) {
            if (! $entry->getDateTime2()) continue;
            
            if ($this->day->getDateTimeStart()->format('Y-m-d') >= $entry->getDateTime1()->format('Y-m-d')
                && $this->day->getDateTimeStart()->format('Y-m-d') <= $entry->getDateTime2()->format('Y-m-d')) {
                    echo '<a href="' . $this->url('kofus_system', array('controller' => 'node', 'action' => 'edit', 'id' => $entry->getNodeId()), true) . '">';
                    echo ' <i class="fa fa-square pull-left" data-toggle="tooltip" title="'.$this->escapeHtmlAttr($entry->getTitle()).'" style="color: '.$entry->getColor().'"></i>';
                    echo '</a>';
            }
       }
       ?>
       
       <?php foreach ($this->day->getHolidays() as $holiday) : ?>
           <?php if ($holiday['type'] !== 'icon') continue ?>
           
           <?php if ($holiday['label'] == 'new') : ?>
               <i class="wi wi-moon-new pull-left" data-toggle="tooltip" title="Neumond" style="color: gray"></i>
           <?php elseif ($holiday['label'] == 'full') : ?>
               <i class="wi wi-moon-full pull-left" data-toggle="tooltip" title="Vollmond" style="color: gray"></i>
           <?php elseif ($holiday['label'] == 'waxing') : ?>
               <i class="wi wi-moon-waxing-crescent-4 pull-left" data-toggle="tooltip" title="Zunehmender Mond" style="color: gray"></i>
           <?php elseif ($holiday['label'] == 'waning') : ?>
               <i class="wi wi-moon-waning-crescent-2 pull-left" data-toggle="tooltip" title="Abnehmender Mond" style="color: gray"></i>
               
           <?php endif ?>
           
       <?php endforeach ?>
       
       <strong class="pull-right"><?php echo $this->day->getDateTimeStart()->format('d') ?></strong><br>
       
       	                           

       <?php foreach ($this->day->getHolidays() as $holiday) : ?>
                  <?php if ($holiday['type'] != 'text') continue ?>
           <?php echo $holiday['label'] ?><br>
       <?php endforeach ?>

       <?php foreach ($entries as $entry) : ?>
            <?php if ('CALENTB' == $entry->getNodeType()) : ?>
                <a title="<?php echo $this->escapeHtmlAttr($entry->getTitle()) ?>" class="label label-warning" href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'edit', 'id' => $entry->getNodeId()), true) ?>">
                   <?php echo $entry->getTitle(20) ?>
                   <?php if ($entry->getAge($this->day->getDateTimeStart())) : ?>
                        (<?php echo $this->escapeHtml($entry->getAge($this->day->getDateTimeStart())) ?>)
                   <?php endif ?>
                </a><br>
            <?php elseif (! $entry->getDateTime2()) : ?>
                
                <a title="<?php echo $this->escapeHtmlAttr($entry->getTitle()) ?>" class="label label-default" href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'edit', 'id' => $entry->getNodeId()), true) ?>"
                    style="<?php if ($entry->getColor()) echo 'background-color: ' . $entry->getColor() ?>">
                   <?php echo $entry->getTime1(true) ?>
                   <?php echo $entry->getTitle(20) ?>
                </a><br>
           <?php endif ?>
       <?php endforeach ?>
       </td>


