<?php $today = new \DateTime() ?>
       <td <?php
       $css = array();
       
       if (isset($this->month) && $this->day->getDateTimeStart()->format('Y-m') != $this->month->getDateTimeStart()->format('Y-m'))
       	$css[] = 'inactive';
       if ($this->day->isHoliday())
       	$css[] = 'danger';
       if ($this->day->getDateTimeStart()->format('Y-m-d') == $today->format('Y-m-d'))
       	$css[] = 'today';
       if ($css) echo 'class="'.implode(' ', $css).'"';
       ?>>
       
       <?php foreach ($this->day->getHolidays() as $holiday) : ?>
           <?php if ($holiday['type'] !== 'icon') continue ?>
           
           <?php if ($holiday['label'] == 'new') : ?>
               <i class="wi wi-moon-new pull-right" data-toggle="tooltip" title="Neumond"></i>
           <?php elseif ($holiday['label'] == 'full') : ?>
               <i class="wi wi-moon-full pull-right" data-toggle="tooltip" title="Vollmond"></i>
           <?php elseif ($holiday['label'] == 'waxing') : ?>
               <i class="wi wi-moon-waxing-crescent-4 pull-right" data-toggle="tooltip" title="Zunehmender Mond"></i>
           <?php elseif ($holiday['label'] == 'waning') : ?>
               <i class="wi wi-moon-waning-crescent-2 pull-right" data-toggle="tooltip" title="Abnehmender Mond"></i>
               
           <?php endif ?>
           
       <?php endforeach ?>
       	                           

       <strong><?php echo $this->day->getDateTimeStart()->format('d') ?></strong><br>
       <?php foreach ($this->day->getHolidays() as $holiday) : ?>
                  <?php if ($holiday['type'] != 'text') continue ?>
           <?php echo $holiday['label'] ?><br>
       <?php endforeach ?>
       <?php $entries = $this->day->getEntries() ?>
       <?php foreach ($entries as $entry) : ?>
           <a title="<?php echo $this->escapeHtmlAttr($entry->getTitle()) ?>" class="label label-default" href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'edit', 'id' => $entry->getNodeId()), true) ?>">
               <?php echo $entry->getTime1(true) ?>
               <?php echo $entry->getTitle(20) ?>
           </a><br>
       <?php endforeach ?>
       </td>


