<div class="row">
    <div class="col-md-12">
		<h1><?php echo $this->translate('Calendars') ?></h1>
    </div>
	<div class="col-md-9">
		<?php if ($this->entities) : ?>
			<table class="table table-hover">
                <tbody data-link="row" class="rowlink">
                    <?php foreach ($this->entities as $entity) : ?>
    					<tr class="<?php if (! $entity->isEnabled()) echo 'danger' ?>">
    						<td>
                                <a href="<?php echo $this->url('kofus_calendar', array('controller' => 'calendar', 'action' => 'month', 'id' => $entity->getNodeId()), true) ?>">
                                    <?php echo $this->escapeHtml($entity->getTitle()) ?>
                                </a>
    						</td>
    					</tr>
    				<?php endforeach ?>
				</tbody>
			</table>
		<?php else : ?>
            <p><?php echo $this->translate('No entries.') ?></p>
		<?php endif ?>
	</div>
	<div class="col-md-3">
		  <div class="list-group">
		      <a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'add', 'id' => 'CAL'), true) ?>" class="list-group-item">
		          <span class="glyphicon glyphicon-plus"></span>
		          <?php echo $this->translate('Add') ?>
		      </a>
		  </div>
    </div>	
</div>
