<?php 
    $dt = \DateTime::createFromFormat('Y-m-d', $this->month->getDateTimeStart()->format('Y-m-d'));
    $previous = $dt->modify('-5 day')->format('Y-m');
    $next = $dt->modify('+1 month')->modify('+10 day')->format('Y-m');
    $today = new \DateTime();
?>


<div class="row">
	<div class="col-md-12">
        <?php echo $this->nodeNavigation($this->calendar, 'month', $this->calendar->getTitle())->render() ?>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <?php 
                    echo $this->navigation()->menu()
                        ->setContainer($this->navMonths)
                        ->setUlClass('nav navbar-nav navbar-left') 
                ?>
        		<ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
        				<a aria-expanded="false" aria-haspopup="true" role="button" data-toggle="dropdown" class="dropdown-toggle" href="#"><?php echo $this->month->getDateTimeStart()->format('Y') ?> <span class="caret"></span></a>
        				<ul class="dropdown-menu">
        				    <?php foreach ($this->years as $year) : ?>
            				    <li>
                    				<a href="<?php echo $this->url('kofus_calendar', array('controller' => 'calendar', 'action' => 'month', 'id' => $this->month->getCalendar()->getNodeId(), 'id2' => $year . '-' . $this->month->getDateTimeStart()->format('m')), true) ?>">
                                        <?php echo $this->escapehtml($year) ?>            														
                					</a>
                				</li>
            				<?php endforeach ?>
            			</ul>
            		</li>
            	</ul>
            </div>
        </nav>	

        <h3 style="text-align: center">
            <a href="<?php echo $this->url('kofus_calendar', array('controller' => 'calendar', 'action' => 'month', 'id' => $this->calendar->getNodeId(), 'id2' => $previous)) ?>" class="pull-left">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a href="<?php echo $this->url('kofus_calendar', array('controller' => 'calendar', 'action' => 'month', 'id' => $this->calendar->getNodeId(), 'id2' => $next)) ?>" class="pull-right">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
            
            <?php echo $this->translate($this->month->getDateTimeStart()->format('F')) ?>
            <?php echo $this->month->getDateTimeStart()->format('Y') ?>
        </h3>
	   
	   <table class="table calendar calendar-month">
	       <thead>
	           <tr>
	               <th><?php echo $this->translate('Monday') ?></th>
	               <th><?php echo $this->translate('Tuesday') ?></th>
	               <th><?php echo $this->translate('Wednesday') ?></th>
	               <th><?php echo $this->translate('Thursday') ?></th>
	               <th><?php echo $this->translate('Friday') ?></th>
	               <th><?php echo $this->translate('Saturday') ?></th>
	               <th><?php echo $this->translate('Sunday') ?></th>
	           </tr>
	       </thead>
	       <tbody>
	           <?php foreach ($this->month->getWeeks() as $week) : ?>
	               <tr>
	                   <?php foreach ($week->getDays() as $day) : ?>
	                       <?php echo $this->partial('kofus/calendar/calendar/day.phtml', array('day' => $day)) ?>
	                   <?php endforeach ?>
	               </tr>
	           <?php endforeach ?>
	           
	       </tbody>
	   </table>

	   
	</div>
</div>
