<?php 
    $dt = \DateTime::createFromFormat('Y-m-d', $this->month->getDateTimeStart()->format('Y-m-d'));
    $previous = $dt->modify('-5 day')->format('Y-m');
    $next = $dt->modify('+1 month')->modify('+10 day')->format('Y-m');
    $today = new \DateTime();
?>


<div class="row">
	<div class="col-md-12">
        <h1><?php echo $this->calendar->getTitle() ?></h1>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <?php 
                    echo $this->navigation()->menu()
                        ->setContainer($this->navMonths)
                        ->setUlClass('nav navbar-nav navbar-left') 
                ?>
        		<ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
        				<a aria-expanded="false" aria-haspopup="true" role="button" data-toggle="dropdown" class="dropdown-toggle" href="#"><?php echo $this->month->getDateTimeStart()->format('Y') ?> <span class="caret"></span></a>
        				<ul class="dropdown-menu">
        				    <?php foreach ($this->years as $year) : ?>
            				    <li>
                    				<a href="<?php echo $this->url('kofus_calendar', array('controller' => 'calendar', 'action' => 'month', 'id' => $this->month->getCalendar()->getNodeId(), 'id2' => $year . '-' . $this->month->getDateTimeStart()->format('m')), true) ?>">
                                        <?php echo $this->escapehtml($year) ?>            														
                					</a>
                				</li>
            				<?php endforeach ?>
            			</ul>
            		</li>
            	</ul>
            </div>
        </nav>	

        <h3 style="text-align: center">
            <a href="<?php echo $this->url('kofus_calendar', array('controller' => 'calendar', 'action' => 'month', 'id' => $this->calendar->getNodeId(), 'id2' => $previous)) ?>" class="pull-left">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a href="<?php echo $this->url('kofus_calendar', array('controller' => 'calendar', 'action' => 'month', 'id' => $this->calendar->getNodeId(), 'id2' => $next)) ?>" class="pull-right">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
            
            <?php echo $this->translate($this->month->getDateTimeStart()->format('F')) ?>
            <?php echo $this->month->getDateTimeStart()->format('Y') ?>
        </h3>
	   
	   <table class="table calendar calendar-month">
	       <thead>
	           <tr>
	               <th><?php echo $this->translate('Monday') ?></th>
	               <th><?php echo $this->translate('Tuesday') ?></th>
	               <th><?php echo $this->translate('Wednesday') ?></th>
	               <th><?php echo $this->translate('Thursday') ?></th>
	               <th><?php echo $this->translate('Friday') ?></th>
	               <th><?php echo $this->translate('Saturday') ?></th>
	               <th><?php echo $this->translate('Sunday') ?></th>
	           </tr>
	       </thead>
	       <tbody>
	           <?php foreach ($this->month->getWeeks() as $week) : ?>
	               <tr>
	                   <?php foreach ($week->getDays() as $day) : ?>
	                       <td <?php
	                           $css = array();
	                           if ($day->getDateTimeStart()->format('Y-m') != $this->month->getDateTimeStart()->format('Y-m'))
                                    $css[] = 'inactive';
                               if ($day->isHoliday())
                                    $css[] = 'danger';
                               if ($day->getDateTimeStart()->format('Y-m-d') == $today->format('Y-m-d'))
                                   $css[] = 'today';
                               if ($css) echo 'class="'.implode(' ', $css).'"';
	                           ?>>
	                           <strong><?php echo $day->getDateTimeStart()->format('d') ?></strong><br>
	                           <?php foreach ($day->getHolidays() as $holiday) : ?>
	                               <?php echo $holiday['label'] ?><br>
	                           <?php endforeach ?>
	                           <?php $entries = $day->getEntries() ?>
	                           <?php foreach ($entries as $entry) : ?>
	                               <a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'edit', 'id' => $entry->getNodeId()), true) ?>">
    	                               <span class="label label-default" title="<?php echo $this->escapeHtmlAttr($entry->getTitle()) ?>">
        	                               <?php echo $entry->getTime1(true) ?>
        	                               <?php echo $entry->getTitle(20) ?>
    	                               </span>
	                               </a><br>
	                           <?php endforeach ?>
	                       </td>
	                   <?php endforeach ?>
	               </tr>
	           <?php endforeach ?>
	           
	       </tbody>
	   </table>
       <?php echo $this->nodeNavigation($this->calendar, 'month')->render() ?>
	   
	</div>
</div>
