<div class="row">
	<div class="col-md-12">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <?php 
                    echo $this->navigation()->menu()
                        ->setContainer($this->navMonths)
                        ->setUlClass('nav navbar-nav navbar-left') 
                ?>
        		<ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
        				<a aria-expanded="false" aria-haspopup="true" role="button" data-toggle="dropdown" class="dropdown-toggle" href="#"><?php echo $this->month->getDateTimeStart()->format('Y') ?> <span class="caret"></span></a>
        				<ul class="dropdown-menu">
        				    <?php foreach ($this->years as $year) : ?>
            				    <li>
                    				<a href="<?php echo $this->url('kofus_calendar', array('controller' => 'calendar', 'action' => 'month', 'id' => $this->month->getCalendar()->getNodeId(), 'id2' => $year . '-' . $this->month->getDateTimeStart()->format('m')), true) ?>">
                                        <?php echo $this->escapehtml($year) ?>            														
                					</a>
                				</li>
            				<?php endforeach ?>
            			</ul>
            		</li>
            	</ul>
            </div>
        </nav>	

        <h3 style="text-align: center">
            <?php echo $this->translate($this->month->getDateTimeStart()->format('F')) ?>
            <?php echo $this->month->getDateTimeStart()->format('Y') ?>
        </h3>
	   
	   <table class="table">
	       <thead>
	           <tr>
	               <td><?php echo $this->translate('Monday') ?></td>
	               <td><?php echo $this->translate('Tuesday') ?></td>
	               <td><?php echo $this->translate('Wednesday') ?></td>
	               <td><?php echo $this->translate('Thursday') ?></td>
	               <td><?php echo $this->translate('Friday') ?></td>
	               <td><?php echo $this->translate('Saturday') ?></td>
	               <td><?php echo $this->translate('Sunday') ?></td>
	           </tr>
	       </thead>
	       <tbody>
	           <?php foreach ($this->month->getWeeks() as $week) : ?>
	               <tr>
	                   <?php foreach ($week->getDays() as $day) : ?>
	                       <td>
	                           <?php echo $day->getDateTimeStart()->format('d') ?><br>
	                           <?php $entries = $day->getEntries() ?>
	                           <?php foreach ($entries as $entry) : ?>
	                               <a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'edit', 'id' => $entry->getNodeId()), true) ?>">
    	                               <span class="label label-default">
        	                               <?php echo $entry->getTime1(true) ?>
        	                               <?php echo $entry->getTitle() ?>
    	                               </span>
	                               </a><br>
	                           <?php endforeach ?>
	                       </td>
	                   <?php endforeach ?>
	               </tr>
	           <?php endforeach ?>
	           
	       </tbody>
	   </table>
	</div>
	<div class="col-md-3">
		  <div class="list-group">
		      <a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'add', 'id' => 'CALENT'), true) ?>" class="list-group-item">
		          <span class="glyphicon glyphicon-plus"></span>
		          <?php echo $this->translate('Calendar Entry') ?>
		      </a>
		      <a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'edit', 'id' => $this->month->getCalendar()->getNodeId()), true) ?>" class="list-group-item">
		          <span class="glyphicon glyphicon-pencil"></span>
		          <?php echo $this->translate('Edit') ?>
		      </a>
		      
		  </div>
    </div>	
</div>
